Dev
klaytn/klaytn-docs-ko pull request #95
Opened 2022-03-30 05:11 UTC by terrikwak

2022-03-30 05:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/klaytn/klaytn-docs-ko?pullRequest=95) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/klaytn/klaytn-docs-ko?pullRequest=95) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: klaytndocs<br/>:x: circleci-klaytn<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/klaytn/klaytn-docs-ko?pullRequest=95) it.</sub>

2022-03-31 00:55 UTC, terrikwak commented on docs/dapp/json-rpc/public-en.md
> +- 포셋(Faucet): Baobab 테스트넷을 위한 테스트 KLAY를 얻을 수 있습니다. [포셋](https://docs.klaytn.com/dapp/developer-tools/klaytn-wallet#how-to-receive-baobab-testnet-klay) 바로가기.
```suggestion
- 포셋(Faucet): Baobab 테스트넷을 위한 테스트 KLAY를 얻을 수 있습니다. [포셋](https://docs.klaytn.com/dapp/developer-tools/klaytn-wallet#how-to-receive-baobab-testnet-klay) 바로가기
```

2022-03-31 01:01 UTC, aidan-kwon requested changes
실수로 승인하여 리뷰상태 원복

2022-03-31 01:57 UTC, terrikwak commented
> �실수로 승인하여 리뷰상태 원복

다시 부탁드립니당 ^^ .. ㅎㅎ

2022-03-31 01:57 UTC, terrikwak commented
> > �실수로 승인하여 리뷰상태 원복
> 
> 다시 부탁드립니당 ^^ .. ㅎㅎ

리뷰 굳이 해주실 필요없고, 그냥 번역된 거 반영하는 데 승인이 필요합니당 ㅜ

2022-03-31 01:58 UTC, kjhman21 approved these changes

2022-03-31 02:10 UTC, iv0rish approved these changes

2022-03-31 02:11 UTC, aidan-kwon approved these changes

2022-03-31 02:16 UTC, merged